MIDI_CHANNELS_NUMBER = 16
MIDI_NOTES_NUMBER = 128
MIDI_INSTRUMENTS_NUMBER = 128
TEMPO = 500000
# RATE PER SECOND
QUANTIZATION = 10
SEQUENCE_LENGTH = 5
NOTES_IN_QUANT = MIDI_NOTES_NUMBER * MIDI_INSTRUMENTS_NUMBER
